// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: urhcrziwgqtmrjbixmxq

class SupabaseConfig {
  static const String supabaseUrl = 'https://urhcrziwgqtmrjbixmxq.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaGNyeml3Z3F0bXJqYml4bXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjE4MDcsImV4cCI6MjA3MzUzNzgwN30.Fsh3HiTo0KcI5OXLGBaxC6aaNYkV1Zi1TsDgniLpJOc';
}
